//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloserRepository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Closer_DBEntities : DbContext
    {
        public Closer_DBEntities()
            : base("name=Closer_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_BUYER_INFO> TBL_BUYER_INFO { get; set; }
        public virtual DbSet<TBL_SELLER_INFO> TBL_SELLER_INFO { get; set; }
    }
}
