//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloserRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SELLER_INFO
    {
        public int S_Id { get; set; }
        public string Name { get; set; }
        public string Phone_No { get; set; }
        public string Location { get; set; }
        public string Password { get; set; }
        public string Confirm_Password { get; set; }
        public string Registration_time { get; set; }
        public string Seller_Email { get; set; }
    }
}
